# Build NodeJS Express app using Azure Pipelinesasdf
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.8.0'
  
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install -y build-essential g++
    sudo apt-get install -y g++-4.8
    sudo apt-get install -y libtool pkg-config build-essential autoconf automake
    sudo apt-get install -y libzmq-dev
    
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    pkg-config libzmq --libs
    
    sudo npm install yarn -g
    sudo yarn

    
    
