# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.8.0'
      displayName: 'Install npm'
  - task: CmdLine@2
    inputs:
      script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install -y autoconf build-essential g++-4.8 libtool pkg-config build-essential autoconf automake libzmq-dev
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
      displayName: 'Install build tools'
  - bash: |
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
    displayName: 'install yarn'

  - script: |
      sudo yarn
