# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
name: 'Build Linux and OSX'
jobs:


  - job: BuildOSX
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.8.0'
          displayName: 'Install npm'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          displayName: 'Install python3.6'
      - task: CmdLine@2
        inputs:
          script: |
            brew update
            brew install pkg-config
            brew install zmq
            export PKG_CONFIG_PATH=/usr/local/Cellar/zeromq/4.0.4/lib/pkgconfig/
          displayName: 'Install build tools'
      - script: |
          brew install llvm
          gcc --version
          sudo npm install yarn -g
          sudo npm install zmq
          sudo pip install -r pysrc/requirments.txt
          sudo pip install ./pysrc
          sudo yarn
          sudo yarn package
          #sudo yarn build
          #sudo yarn test
        displayName: 'yarn install'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'artifactName'
          targetPath: 'release/ElectronReact-1.0.0.dmg'
      
      - script: |
          sudo pip install virtualenv
          virtualenv venv -p python3
          venv/bin/pip install -r requirements.txt
          venv/bin/python setup.py develop
        workingDirectory: './pysrc'
      - script: |
          sudo yarn test-python
