# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.8.0'
  
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y
    sudo apt-get install -y g++-4.8
    npm i -g npm@6.2.0
    npm install zmq -g
    npm install -g node-gyp
    npm install yarn -g
    yarn
    
