# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.8.0'
  
- script: |
    add-apt-repository ppa:ubuntu-toolchain-r/test
    apt-get update -y
    apt-get install -y g++-4.8
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    npm i -g npm@6.2.0
    npm install -g node-gyp
    npm install yarn -g
    yarn
    
