# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
name: 'Build Linux and OSX'
jobs:


  - job: BuildOSX
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.8.0'
          displayName: 'Install npm'
      - task: CmdLine@2
        inputs:
          script: |
            brew update
            brew install pkg-config
            brew install zmq
          displayName: 'Install build tools'
      - script: |
          sudo npm install yarn -g
          sudo pip install virtualenv
          virtualenv venv -p python3
          venv/bin/pip install pyinstaller
          sudo npm install -g node-gyp
          sudo yarn
          sudo yarn package
          #sudo yarn build
          #sudo yarn test
        displayName: 'yarn install'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'artifactName'
          targetPath: 'release/ElectronReact-1.0.0.dmg'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.5'
          displayName: 'Install python3.5'
      - script: |
          sudo pip install virtualenv
          virtualenv venv -p python3
          venv/bin/pip install -r requirements.txt
          venv/bin/python setup.py develop
        workingDirectory: './pysrc'
      - script: |
          sudo yarn test-python


  - job: BuildWin
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.8.0'
          displayName: 'Install npm'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.5'
          displayName: 'Install python3.5'
      - task: CmdLine@2
        inputs:
          script: |
            #npm --add-python-to-path='true' --debug install --global windows-build-tools
            pip install pyinstaller
            npm install yarn -g
            yarn
            yarn package
            cd release
            ls
          displayName: 'yarn'
