# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts


phases:
- phase: A
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.8.0'

- script: |
    sleep 4m
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install -y autoconf
    sudo apt-get install -y build-essential g++
    sudo apt-get install -y g++-4.8
    sudo apt-get install -y libtool pkg-config build-essential autoconf automake
    sudo apt-get install -y libzmq-dev
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    sudo npm install yarn -g
    sudo yarn
- phase: B
steps:
- script: |
    echo lol

