# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.8.0'
  
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install -y build-essential g++
    sudo apt-get install -y g++-4.8
    sudo apt-get install libtool pkg-config build-essential autoconf automake
    sudo apt-get install -y libzmq-dev
    export CXX="g++-4.8"
    
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    sudo apt-get update && sudo apt-get install yarn
    
    echo gcc version
    gcc -v
    echo make version
    make -v
    echo node version
    node -v
    echo npm version
    npm -v
    echo yarn version
    npm install yarn -g
    sudo rm -rf node_modules &&
    sudo npm cache clean &&
    yarn -v

    #npm i -g npm@6.2.0
    # sudo npm install zmq -g --unsafe-perm=true --allow-root 
    # npm install -g node-gyp
    
    yarn
    
